config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    :registrations => 'users/registrations',
    # :sessions => 'users/sessions',
  }
  # as :user do
  #   get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
  #   put 'users' => 'devise/registrations#update', :as => 'user_registration'
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  resources :posts
  resources :products do
    get 'download'
  end
  resources :users do
    member do
      get :likes
    end
  end
  resources :favorites, only: [:create, :destroy]
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :check_admin, only: [:new, :create, :edit, :update]
  
  def new
    @product = Product.new
  end
  
  def show
    @products = Product.all.order("created_at DESC").limit(1)
  end
  
  def create
    upload_file = create_params[:data]
    content = {}
    content[:data] = upload_file.read
    content[:filename] = upload_file.original_filename
    @product = Product.new(content)
    if @product.save
      redirect_to controller: :posts, action: :index
    end
  end
  
  def download
    products = Product.find(params[:product_id])
    send_data(products.data, filename: products.filename)
  end
  
  private
  def create_params
    params.require(:product).permit(:data)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/new.html.erb
<div class="contents row">
  <div class="container">
  <h4>ソフトウェアアップロード</h4>
  <p> ※ zipファイルにしてからアップロードしてください</p>
    <%= form_for (@product) do |f| %>
    <div class="form-group">
      <%= f.file_field :data, class: "shadow-sm form-control" %>
    </div>
      <%= f.submit "アップロード", class: "btn btn-info mt-3 mb-3" %>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="contents row">
  <div class="container">
  <h4>ソフトダウンロードページ</h4>
  <% @products.each do |product| %>
    <p>※ 以下のボタンをクリックするとダウンロードが開始されます</p>
    <p><%= product[:created_at].strftime('%Y年%m月%d日 更新') %></p>
    <p><%= button_to product.filename, product_download_path(product.id), method: :get, class: "btn btn-info btn-lg" %></p>
  <% end %>
  </div>
</div>